### ISSUE TITLE
about avg_anyobj

### ISSUE THREAD

**Issue by chengweige** [leon-liangwu/MaskYolo_Caffe#34]
add 
avg_anyobj -= avg_obj; ?
before 
avg_anyobj /= (w_*h_*n_*batch_ - obj_count);
all right？

**Comment by leon-liangwu** [comment]
hi @chengweige  why should that be added?
avg_anyobj is actually for no-obj confidence.

**Comment by chengweige** [comment]
for region_loss_layer, 
avg_anyobj += l_output[index + 4*w_*h_] is used for all anchor box, 
avg_obj += l_output[best_index + 4*w_*h_] is used for the matched anchor box,
so does avg_anyobj means all the confidence including the object's confidence?

**Comment by leon-liangwu** [comment]
@chengweige  yes I see. If you refer to the original darknet implementation. You can find that the author didn't do the subtraction either.
Because the positive places are much less than the non-objects, the outcomes will be similar in both cases. What's more. This is value does not affect the training procedure.
